import ast
import logging
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from fmlwright.core import data_sources, preprocessing
from tensorflow.keras.models import load_model

log = logging.getLogger(__name__)


class BasePredictor:
    """Base predictor class."""

    def __init__(self, model_location, categories, conf_location):
        """Initialize the predictor with a model.

        Args:
            model_location (str): path to the root directory for the models.
            categories (list): List of categories.
            conf_location (str): path to config location.
        """
        self._model = {}

        self.model_type = None

        self.conf = None
        self.input_shape = None
        self.model_location = Path(model_location)
        self.conf_location = Path(conf_location)
        self.categories = categories

    def load_configuration(self, conf_location=None):
        """Load configuration file.

        If conf_location is none, it will use the one set in init.

        Args:
            conf_location (str): path to config location.
        """
        self.conf = data_sources.load_yaml(
            conf_location if conf_location else self.conf_location
        )
        self.input_shape = ast.literal_eval(self.conf["nn_structure"]["input_shape"])

    def load_model(self, model_location=None):
        """Load the generator model.

        If model_location is none, it will use the one set during initialization. The
        configuration file used in init will be used, if none is set. The model assumes that the
        generator file is called generator.h5.

        Args:
            model_location (Path): path to the root directory for the models.
        """
        model_location = model_location if model_location else self.model_location

        if not self.conf:
            self.load_configuration()

        for _cat in self.categories:
            log.info(f"Loading model for category: {_cat}.")
            self._model[_cat] = load_model(
                model_location / _cat / "generator.h5", compile=False
            )

    def preprocess_image(self, img):
        """Preprocess the image.

        It is padded to the config image shape and normalize between -1 and 1 for the generator.

        Args:
            img: Image loaded using cv2.

        Returns:
            Preprocessed and normalized image between -1 and 1.
        """
        preprocessed_img = preprocessing.resize_and_pad(
            img, size=(self.input_shape[0], self.input_shape[1]), pad_color=255
        )
        preprocessed_img = data_sources.normalize_image(preprocessed_img)
        return preprocessed_img

    def visualize_predictions(self, img, predictions):
        """Visualize the predictions.

        Args:
            img: Image as it was loaded in using cv2.
            predictions (dictionary): Dictioanry of predictions generated by the `predict` function.

        Returns:
            Image with generated predictions, three items per row.
        """
        preprocessed_img = self.preprocess_image(img)
        preprocessed_img = (preprocessed_img * 0.5) + 0.5
        n_predictions = len(predictions.keys())

        fig, axes = plt.subplots(
            figsize=(15, 3 * n_predictions),
            nrows=int(np.ceil((n_predictions + 1) / 3)),
            ncols=3,
        )
        input_results = [preprocessed_img] + list(predictions.values())
        titles = ["input"] + [
            f"{comb[0]}_{comb[1]}" for comb in list(predictions.keys())
        ]

        i = 0
        for title, img, ax in zip(titles, input_results, axes.flatten()):
            plt.subplot(ax)
            plt.title(f"{i}_{title}", fontweight="bold")
            plt.imshow(img)
            plt.axis("off")
            i += 1

        for ax in axes.flatten():
            plt.subplot(ax)
            plt.axis("off")
        plt.tight_layout()
        return fig, axes
